// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schafkopf.proto

package schafkopf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Spieltyp int32

const (
	Spieltyp_Undefiniert Spieltyp = 0
	Spieltyp_Ramsch      Spieltyp = 1
	Spieltyp_Sauspiel    Spieltyp = 2
	Spieltyp_Wenz        Spieltyp = 3
	Spieltyp_Geier       Spieltyp = 4
	Spieltyp_Solo        Spieltyp = 5
)

var Spieltyp_name = map[int32]string{
	0: "Undefiniert",
	1: "Ramsch",
	2: "Sauspiel",
	3: "Wenz",
	4: "Geier",
	5: "Solo",
}

var Spieltyp_value = map[string]int32{
	"Undefiniert": 0,
	"Ramsch":      1,
	"Sauspiel":    2,
	"Wenz":        3,
	"Geier":       4,
	"Solo":        5,
}

func (x Spieltyp) String() string {
	return proto.EnumName(Spieltyp_name, int32(x))
}

func (Spieltyp) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7593a9a9fb0342c6, []int{0}
}

type Wert int32

const (
	Wert_Keiner Wert = 0
	Wert_Sieben Wert = 1
	Wert_Acht   Wert = 2
	Wert_Neun   Wert = 3
	Wert_Unter  Wert = 4
	Wert_Ober   Wert = 5
	Wert_Koenig Wert = 6
	Wert_Zehn   Wert = 7
	Wert_Sau    Wert = 8
)

var Wert_name = map[int32]string{
	0: "Keiner",
	1: "Sieben",
	2: "Acht",
	3: "Neun",
	4: "Unter",
	5: "Ober",
	6: "Koenig",
	7: "Zehn",
	8: "Sau",
}

var Wert_value = map[string]int32{
	"Keiner": 0,
	"Sieben": 1,
	"Acht":   2,
	"Neun":   3,
	"Unter":  4,
	"Ober":   5,
	"Koenig": 6,
	"Zehn":   7,
	"Sau":    8,
}

func (x Wert) String() string {
	return proto.EnumName(Wert_name, int32(x))
}

func (Wert) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7593a9a9fb0342c6, []int{1}
}

type Farbe int32

const (
	Farbe_Natura   Farbe = 0
	Farbe_Schellen Farbe = 1
	Farbe_Herz     Farbe = 2
	Farbe_Grass    Farbe = 3
	Farbe_Eichel   Farbe = 4
)

var Farbe_name = map[int32]string{
	0: "Natura",
	1: "Schellen",
	2: "Herz",
	3: "Grass",
	4: "Eichel",
}

var Farbe_value = map[string]int32{
	"Natura":   0,
	"Schellen": 1,
	"Herz":     2,
	"Grass":    3,
	"Eichel":   4,
}

func (x Farbe) String() string {
	return proto.EnumName(Farbe_name, int32(x))
}

func (Farbe) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7593a9a9fb0342c6, []int{2}
}

type Message struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_7593a9a9fb0342c6, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_7593a9a9fb0342c6, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_7593a9a9fb0342c6, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type PlayerId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerId) Reset()         { *m = PlayerId{} }
func (m *PlayerId) String() string { return proto.CompactTextString(m) }
func (*PlayerId) ProtoMessage()    {}
func (*PlayerId) Descriptor() ([]byte, []int) {
	return fileDescriptor_7593a9a9fb0342c6, []int{3}
}

func (m *PlayerId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerId.Unmarshal(m, b)
}
func (m *PlayerId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerId.Marshal(b, m, deterministic)
}
func (m *PlayerId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerId.Merge(m, src)
}
func (m *PlayerId) XXX_Size() int {
	return xxx_messageInfo_PlayerId.Size(m)
}
func (m *PlayerId) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerId.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerId proto.InternalMessageInfo

func (m *PlayerId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DoppelRequest struct {
	Doppeln              bool     `protobuf:"varint,1,opt,name=doppeln,proto3" json:"doppeln,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoppelRequest) Reset()         { *m = DoppelRequest{} }
func (m *DoppelRequest) String() string { return proto.CompactTextString(m) }
func (*DoppelRequest) ProtoMessage()    {}
func (*DoppelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7593a9a9fb0342c6, []int{4}
}

func (m *DoppelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoppelRequest.Unmarshal(m, b)
}
func (m *DoppelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoppelRequest.Marshal(b, m, deterministic)
}
func (m *DoppelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoppelRequest.Merge(m, src)
}
func (m *DoppelRequest) XXX_Size() int {
	return xxx_messageInfo_DoppelRequest.Size(m)
}
func (m *DoppelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoppelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoppelRequest proto.InternalMessageInfo

func (m *DoppelRequest) GetDoppeln() bool {
	if m != nil {
		return m.Doppeln
	}
	return false
}

type SpielKarteRequest struct {
	Karte                *Karte   `protobuf:"bytes,1,opt,name=karte,proto3" json:"karte,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpielKarteRequest) Reset()         { *m = SpielKarteRequest{} }
func (m *SpielKarteRequest) String() string { return proto.CompactTextString(m) }
func (*SpielKarteRequest) ProtoMessage()    {}
func (*SpielKarteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7593a9a9fb0342c6, []int{5}
}

func (m *SpielKarteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpielKarteRequest.Unmarshal(m, b)
}
func (m *SpielKarteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpielKarteRequest.Marshal(b, m, deterministic)
}
func (m *SpielKarteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpielKarteRequest.Merge(m, src)
}
func (m *SpielKarteRequest) XXX_Size() int {
	return xxx_messageInfo_SpielKarteRequest.Size(m)
}
func (m *SpielKarteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SpielKarteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SpielKarteRequest proto.InternalMessageInfo

func (m *SpielKarteRequest) GetKarte() *Karte {
	if m != nil {
		return m.Karte
	}
	return nil
}

type GameEvent struct {
	// Types that are valid to be assigned to Eventtype:
	//	*GameEvent_Start
	//	*GameEvent_ErsteHand
	//	*GameEvent_ZweiteHand
	//	*GameEvent_Spiel
	//	*GameEvent_Doppler
	//	*GameEvent_Gespielt
	//	*GameEvent_Ende
	Eventtype            isGameEvent_Eventtype `protobuf_oneof:"eventtype"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GameEvent) Reset()         { *m = GameEvent{} }
func (m *GameEvent) String() string { return proto.CompactTextString(m) }
func (*GameEvent) ProtoMessage()    {}
func (*GameEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_7593a9a9fb0342c6, []int{6}
}

func (m *GameEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameEvent.Unmarshal(m, b)
}
func (m *GameEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameEvent.Marshal(b, m, deterministic)
}
func (m *GameEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameEvent.Merge(m, src)
}
func (m *GameEvent) XXX_Size() int {
	return xxx_messageInfo_GameEvent.Size(m)
}
func (m *GameEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_GameEvent.DiscardUnknown(m)
}

var xxx_messageInfo_GameEvent proto.InternalMessageInfo

type isGameEvent_Eventtype interface {
	isGameEvent_Eventtype()
}

type GameEvent_Start struct {
	Start *Spielstart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type GameEvent_ErsteHand struct {
	ErsteHand *Hand `protobuf:"bytes,2,opt,name=erste_hand,json=ersteHand,proto3,oneof"`
}

type GameEvent_ZweiteHand struct {
	ZweiteHand *Hand `protobuf:"bytes,3,opt,name=zweite_hand,json=zweiteHand,proto3,oneof"`
}

type GameEvent_Spiel struct {
	Spiel *Spieldeklaration `protobuf:"bytes,5,opt,name=spiel,proto3,oneof"`
}

type GameEvent_Doppler struct {
	Doppler *Doppler `protobuf:"bytes,6,opt,name=doppler,proto3,oneof"`
}

type GameEvent_Gespielt struct {
	Gespielt *Karte `protobuf:"bytes,7,opt,name=gespielt,proto3,oneof"`
}

type GameEvent_Ende struct {
	Ende *Spielende `protobuf:"bytes,8,opt,name=ende,proto3,oneof"`
}

func (*GameEvent_Start) isGameEvent_Eventtype() {}

func (*GameEvent_ErsteHand) isGameEvent_Eventtype() {}

func (*GameEvent_ZweiteHand) isGameEvent_Eventtype() {}

func (*GameEvent_Spiel) isGameEvent_Eventtype() {}

func (*GameEvent_Doppler) isGameEvent_Eventtype() {}

func (*GameEvent_Gespielt) isGameEvent_Eventtype() {}

func (*GameEvent_Ende) isGameEvent_Eventtype() {}

func (m *GameEvent) GetEventtype() isGameEvent_Eventtype {
	if m != nil {
		return m.Eventtype
	}
	return nil
}

func (m *GameEvent) GetStart() *Spielstart {
	if x, ok := m.GetEventtype().(*GameEvent_Start); ok {
		return x.Start
	}
	return nil
}

func (m *GameEvent) GetErsteHand() *Hand {
	if x, ok := m.GetEventtype().(*GameEvent_ErsteHand); ok {
		return x.ErsteHand
	}
	return nil
}

func (m *GameEvent) GetZweiteHand() *Hand {
	if x, ok := m.GetEventtype().(*GameEvent_ZweiteHand); ok {
		return x.ZweiteHand
	}
	return nil
}

func (m *GameEvent) GetSpiel() *Spieldeklaration {
	if x, ok := m.GetEventtype().(*GameEvent_Spiel); ok {
		return x.Spiel
	}
	return nil
}

func (m *GameEvent) GetDoppler() *Doppler {
	if x, ok := m.GetEventtype().(*GameEvent_Doppler); ok {
		return x.Doppler
	}
	return nil
}

func (m *GameEvent) GetGespielt() *Karte {
	if x, ok := m.GetEventtype().(*GameEvent_Gespielt); ok {
		return x.Gespielt
	}
	return nil
}

func (m *GameEvent) GetEnde() *Spielende {
	if x, ok := m.GetEventtype().(*GameEvent_Ende); ok {
		return x.Ende
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GameEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GameEvent_Start)(nil),
		(*GameEvent_ErsteHand)(nil),
		(*GameEvent_ZweiteHand)(nil),
		(*GameEvent_Spiel)(nil),
		(*GameEvent_Doppler)(nil),
		(*GameEvent_Gespielt)(nil),
		(*GameEvent_Ende)(nil),
	}
}

// The request message containing the user's name.
type Spielstart struct {
	Players              []string `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	FirstPlayer          uint32   `protobuf:"varint,3,opt,name=first_player,json=firstPlayer,proto3" json:"first_player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Spielstart) Reset()         { *m = Spielstart{} }
func (m *Spielstart) String() string { return proto.CompactTextString(m) }
func (*Spielstart) ProtoMessage()    {}
func (*Spielstart) Descriptor() ([]byte, []int) {
	return fileDescriptor_7593a9a9fb0342c6, []int{7}
}

func (m *Spielstart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Spielstart.Unmarshal(m, b)
}
func (m *Spielstart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Spielstart.Marshal(b, m, deterministic)
}
func (m *Spielstart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Spielstart.Merge(m, src)
}
func (m *Spielstart) XXX_Size() int {
	return xxx_messageInfo_Spielstart.Size(m)
}
func (m *Spielstart) XXX_DiscardUnknown() {
	xxx_messageInfo_Spielstart.DiscardUnknown(m)
}

var xxx_messageInfo_Spielstart proto.InternalMessageInfo

func (m *Spielstart) GetPlayers() []string {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *Spielstart) GetFirstPlayer() uint32 {
	if m != nil {
		return m.FirstPlayer
	}
	return 0
}

type Spielende struct {
	Sieger               []string `protobuf:"bytes,1,rep,name=sieger,proto3" json:"sieger,omitempty"`
	Verlierer            []string `protobuf:"bytes,2,rep,name=verlierer,proto3" json:"verlierer,omitempty"`
	Betrag               float32  `protobuf:"fixed32,3,opt,name=betrag,proto3" json:"betrag,omitempty"`
	Kommentar            string   `protobuf:"bytes,4,opt,name=kommentar,proto3" json:"kommentar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Spielende) Reset()         { *m = Spielende{} }
func (m *Spielende) String() string { return proto.CompactTextString(m) }
func (*Spielende) ProtoMessage()    {}
func (*Spielende) Descriptor() ([]byte, []int) {
	return fileDescriptor_7593a9a9fb0342c6, []int{8}
}

func (m *Spielende) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Spielende.Unmarshal(m, b)
}
func (m *Spielende) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Spielende.Marshal(b, m, deterministic)
}
func (m *Spielende) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Spielende.Merge(m, src)
}
func (m *Spielende) XXX_Size() int {
	return xxx_messageInfo_Spielende.Size(m)
}
func (m *Spielende) XXX_DiscardUnknown() {
	xxx_messageInfo_Spielende.DiscardUnknown(m)
}

var xxx_messageInfo_Spielende proto.InternalMessageInfo

func (m *Spielende) GetSieger() []string {
	if m != nil {
		return m.Sieger
	}
	return nil
}

func (m *Spielende) GetVerlierer() []string {
	if m != nil {
		return m.Verlierer
	}
	return nil
}

func (m *Spielende) GetBetrag() float32 {
	if m != nil {
		return m.Betrag
	}
	return 0
}

func (m *Spielende) GetKommentar() string {
	if m != nil {
		return m.Kommentar
	}
	return ""
}

type Doppler struct {
	Spieler              string   `protobuf:"bytes,1,opt,name=Spieler,proto3" json:"Spieler,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Doppler) Reset()         { *m = Doppler{} }
func (m *Doppler) String() string { return proto.CompactTextString(m) }
func (*Doppler) ProtoMessage()    {}
func (*Doppler) Descriptor() ([]byte, []int) {
	return fileDescriptor_7593a9a9fb0342c6, []int{9}
}

func (m *Doppler) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Doppler.Unmarshal(m, b)
}
func (m *Doppler) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Doppler.Marshal(b, m, deterministic)
}
func (m *Doppler) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Doppler.Merge(m, src)
}
func (m *Doppler) XXX_Size() int {
	return xxx_messageInfo_Doppler.Size(m)
}
func (m *Doppler) XXX_DiscardUnknown() {
	xxx_messageInfo_Doppler.DiscardUnknown(m)
}

var xxx_messageInfo_Doppler proto.InternalMessageInfo

func (m *Doppler) GetSpieler() string {
	if m != nil {
		return m.Spieler
	}
	return ""
}

type Hand struct {
	Received             []*Karte `protobuf:"bytes,1,rep,name=received,proto3" json:"received,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hand) Reset()         { *m = Hand{} }
func (m *Hand) String() string { return proto.CompactTextString(m) }
func (*Hand) ProtoMessage()    {}
func (*Hand) Descriptor() ([]byte, []int) {
	return fileDescriptor_7593a9a9fb0342c6, []int{10}
}

func (m *Hand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hand.Unmarshal(m, b)
}
func (m *Hand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hand.Marshal(b, m, deterministic)
}
func (m *Hand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hand.Merge(m, src)
}
func (m *Hand) XXX_Size() int {
	return xxx_messageInfo_Hand.Size(m)
}
func (m *Hand) XXX_DiscardUnknown() {
	xxx_messageInfo_Hand.DiscardUnknown(m)
}

var xxx_messageInfo_Hand proto.InternalMessageInfo

func (m *Hand) GetReceived() []*Karte {
	if m != nil {
		return m.Received
	}
	return nil
}

type Spieldeklaration struct {
	HatSpiel             bool     `protobuf:"varint,1,opt,name=hat_spiel,json=hatSpiel,proto3" json:"hat_spiel,omitempty"`
	Spieler              string   `protobuf:"bytes,2,opt,name=spieler,proto3" json:"spieler,omitempty"`
	Spieltyp             Spieltyp `protobuf:"varint,3,opt,name=spieltyp,proto3,enum=schafkopf.Spieltyp" json:"spieltyp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Spieldeklaration) Reset()         { *m = Spieldeklaration{} }
func (m *Spieldeklaration) String() string { return proto.CompactTextString(m) }
func (*Spieldeklaration) ProtoMessage()    {}
func (*Spieldeklaration) Descriptor() ([]byte, []int) {
	return fileDescriptor_7593a9a9fb0342c6, []int{11}
}

func (m *Spieldeklaration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Spieldeklaration.Unmarshal(m, b)
}
func (m *Spieldeklaration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Spieldeklaration.Marshal(b, m, deterministic)
}
func (m *Spieldeklaration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Spieldeklaration.Merge(m, src)
}
func (m *Spieldeklaration) XXX_Size() int {
	return xxx_messageInfo_Spieldeklaration.Size(m)
}
func (m *Spieldeklaration) XXX_DiscardUnknown() {
	xxx_messageInfo_Spieldeklaration.DiscardUnknown(m)
}

var xxx_messageInfo_Spieldeklaration proto.InternalMessageInfo

func (m *Spieldeklaration) GetHatSpiel() bool {
	if m != nil {
		return m.HatSpiel
	}
	return false
}

func (m *Spieldeklaration) GetSpieler() string {
	if m != nil {
		return m.Spieler
	}
	return ""
}

func (m *Spieldeklaration) GetSpieltyp() Spieltyp {
	if m != nil {
		return m.Spieltyp
	}
	return Spieltyp_Undefiniert
}

type Spiel struct {
	Spieltyp             Spieltyp `protobuf:"varint,1,opt,name=spieltyp,proto3,enum=schafkopf.Spieltyp" json:"spieltyp,omitempty"`
	Farbe                Farbe    `protobuf:"varint,2,opt,name=farbe,proto3,enum=schafkopf.Farbe" json:"farbe,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Spiel) Reset()         { *m = Spiel{} }
func (m *Spiel) String() string { return proto.CompactTextString(m) }
func (*Spiel) ProtoMessage()    {}
func (*Spiel) Descriptor() ([]byte, []int) {
	return fileDescriptor_7593a9a9fb0342c6, []int{12}
}

func (m *Spiel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Spiel.Unmarshal(m, b)
}
func (m *Spiel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Spiel.Marshal(b, m, deterministic)
}
func (m *Spiel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Spiel.Merge(m, src)
}
func (m *Spiel) XXX_Size() int {
	return xxx_messageInfo_Spiel.Size(m)
}
func (m *Spiel) XXX_DiscardUnknown() {
	xxx_messageInfo_Spiel.DiscardUnknown(m)
}

var xxx_messageInfo_Spiel proto.InternalMessageInfo

func (m *Spiel) GetSpieltyp() Spieltyp {
	if m != nil {
		return m.Spieltyp
	}
	return Spieltyp_Undefiniert
}

func (m *Spiel) GetFarbe() Farbe {
	if m != nil {
		return m.Farbe
	}
	return Farbe_Natura
}

type Karte struct {
	Wert                 Wert     `protobuf:"varint,1,opt,name=wert,proto3,enum=schafkopf.Wert" json:"wert,omitempty"`
	Farbe                Farbe    `protobuf:"varint,2,opt,name=farbe,proto3,enum=schafkopf.Farbe" json:"farbe,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Karte) Reset()         { *m = Karte{} }
func (m *Karte) String() string { return proto.CompactTextString(m) }
func (*Karte) ProtoMessage()    {}
func (*Karte) Descriptor() ([]byte, []int) {
	return fileDescriptor_7593a9a9fb0342c6, []int{13}
}

func (m *Karte) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Karte.Unmarshal(m, b)
}
func (m *Karte) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Karte.Marshal(b, m, deterministic)
}
func (m *Karte) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Karte.Merge(m, src)
}
func (m *Karte) XXX_Size() int {
	return xxx_messageInfo_Karte.Size(m)
}
func (m *Karte) XXX_DiscardUnknown() {
	xxx_messageInfo_Karte.DiscardUnknown(m)
}

var xxx_messageInfo_Karte proto.InternalMessageInfo

func (m *Karte) GetWert() Wert {
	if m != nil {
		return m.Wert
	}
	return Wert_Keiner
}

func (m *Karte) GetFarbe() Farbe {
	if m != nil {
		return m.Farbe
	}
	return Farbe_Natura
}

func init() {
	proto.RegisterEnum("schafkopf.Spieltyp", Spieltyp_name, Spieltyp_value)
	proto.RegisterEnum("schafkopf.Wert", Wert_name, Wert_value)
	proto.RegisterEnum("schafkopf.Farbe", Farbe_name, Farbe_value)
	proto.RegisterType((*Message)(nil), "schafkopf.Message")
	proto.RegisterType((*Empty)(nil), "schafkopf.Empty")
	proto.RegisterType((*Response)(nil), "schafkopf.Response")
	proto.RegisterType((*PlayerId)(nil), "schafkopf.PlayerId")
	proto.RegisterType((*DoppelRequest)(nil), "schafkopf.DoppelRequest")
	proto.RegisterType((*SpielKarteRequest)(nil), "schafkopf.SpielKarteRequest")
	proto.RegisterType((*GameEvent)(nil), "schafkopf.GameEvent")
	proto.RegisterType((*Spielstart)(nil), "schafkopf.Spielstart")
	proto.RegisterType((*Spielende)(nil), "schafkopf.Spielende")
	proto.RegisterType((*Doppler)(nil), "schafkopf.Doppler")
	proto.RegisterType((*Hand)(nil), "schafkopf.Hand")
	proto.RegisterType((*Spieldeklaration)(nil), "schafkopf.Spieldeklaration")
	proto.RegisterType((*Spiel)(nil), "schafkopf.Spiel")
	proto.RegisterType((*Karte)(nil), "schafkopf.Karte")
}

func init() {
	proto.RegisterFile("schafkopf.proto", fileDescriptor_7593a9a9fb0342c6)
}

var fileDescriptor_7593a9a9fb0342c6 = []byte{
	// 848 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x6d, 0x8f, 0xdb, 0x44,
	0x10, 0x4e, 0x9c, 0x38, 0xb1, 0x27, 0xe9, 0x9d, 0x59, 0x5e, 0x64, 0x5d, 0x8b, 0x04, 0xae, 0x84,
	0xca, 0x09, 0x8e, 0x92, 0x22, 0x81, 0xe0, 0x03, 0xb4, 0xea, 0xd1, 0x54, 0x55, 0x0b, 0x72, 0x5a,
	0x55, 0xe2, 0xcb, 0xb1, 0x89, 0x27, 0xc9, 0xea, 0x9c, 0xb5, 0xd9, 0xdd, 0xdc, 0x91, 0xfb, 0x61,
	0xfc, 0x2c, 0x7e, 0x03, 0xda, 0x59, 0x3b, 0x71, 0x43, 0x40, 0xf7, 0xcd, 0x33, 0xf3, 0x3c, 0xcf,
	0xce, 0xce, 0xce, 0x8c, 0xe1, 0x58, 0xcf, 0x96, 0x7c, 0x7e, 0x59, 0x94, 0xf3, 0xb3, 0x52, 0x15,
	0xa6, 0x60, 0xe1, 0xd6, 0x91, 0x7c, 0x0c, 0xfd, 0x97, 0xa8, 0x35, 0x5f, 0x20, 0x63, 0xd0, 0x35,
	0xf8, 0xa7, 0x89, 0xdb, 0x9f, 0xb4, 0x1f, 0x84, 0x29, 0x7d, 0x27, 0x7d, 0xf0, 0xcf, 0x57, 0xa5,
	0xd9, 0x24, 0xdf, 0x41, 0x90, 0xa2, 0x2e, 0x0b, 0xa9, 0x91, 0xc5, 0xd0, 0xd7, 0xeb, 0xd9, 0x0c,
	0xb5, 0x26, 0x6c, 0x90, 0xd6, 0xe6, 0x56, 0xc2, 0x6b, 0x48, 0x9c, 0x40, 0xf0, 0x6b, 0xce, 0x37,
	0xa8, 0x9e, 0x67, 0xec, 0x08, 0x3c, 0x91, 0x55, 0x07, 0x78, 0x22, 0x4b, 0x3e, 0x87, 0x3b, 0x4f,
	0x8b, 0xb2, 0xc4, 0x3c, 0xc5, 0x3f, 0xd6, 0xa8, 0x8d, 0x95, 0xce, 0xc8, 0x21, 0x6b, 0xe9, 0xca,
	0x4c, 0x7e, 0x80, 0xf7, 0x26, 0xa5, 0xc0, 0xfc, 0x05, 0x57, 0x06, 0x6b, 0xf8, 0x67, 0xe0, 0x5f,
	0x5a, 0x9b, 0xc0, 0x83, 0x51, 0x74, 0xb6, 0xbb, 0xa9, 0xc3, 0xb9, 0x70, 0xf2, 0xb7, 0x07, 0xe1,
	0x33, 0xbe, 0xc2, 0xf3, 0x2b, 0x94, 0x86, 0x7d, 0x09, 0xbe, 0x36, 0x5c, 0x99, 0x8a, 0xf5, 0x61,
	0x83, 0x45, 0x47, 0x50, 0x70, 0xdc, 0x4a, 0x1d, 0x8a, 0x3d, 0x04, 0x40, 0xa5, 0x0d, 0x5e, 0x2c,
	0xb9, 0xcc, 0xe8, 0x6a, 0x83, 0xd1, 0x71, 0x83, 0x33, 0xe6, 0x32, 0x1b, 0xb7, 0xd2, 0x90, 0x40,
	0xd6, 0x60, 0x23, 0x18, 0xdc, 0x5c, 0xa3, 0xa8, 0x29, 0x9d, 0xff, 0xa2, 0x80, 0x43, 0x11, 0xe7,
	0x11, 0xf8, 0xda, 0x1e, 0x1e, 0xfb, 0x84, 0xbe, 0xbb, 0x9f, 0x54, 0x86, 0x97, 0x39, 0x57, 0xdc,
	0x88, 0x42, 0x52, 0x6a, 0xd6, 0xc7, 0xce, 0x5c, 0xb9, 0x72, 0x54, 0x71, 0x8f, 0x68, 0xac, 0x41,
	0x7b, 0xea, 0x22, 0xe3, 0x56, 0x5a, 0x83, 0xd8, 0x19, 0x04, 0x0b, 0x24, 0xaa, 0x89, 0xfb, 0x87,
	0x4b, 0x36, 0x6e, 0xa5, 0x5b, 0x0c, 0x3b, 0x85, 0x2e, 0xca, 0x0c, 0xe3, 0x80, 0xb0, 0x1f, 0xec,
	0xe7, 0x64, 0x63, 0xe3, 0x56, 0x4a, 0x98, 0x27, 0x03, 0x08, 0xd1, 0x96, 0xd7, 0x6c, 0x4a, 0x4c,
	0x9e, 0x03, 0xec, 0x4a, 0x69, 0x5f, 0xb5, 0xa4, 0x16, 0xb0, 0x0d, 0xd3, 0x79, 0x10, 0xa6, 0xb5,
	0xc9, 0x3e, 0x85, 0xe1, 0x5c, 0x28, 0x6d, 0x2e, 0x9c, 0x83, 0x4a, 0x75, 0x27, 0x1d, 0x90, 0xcf,
	0x75, 0x4d, 0x72, 0x0d, 0xe1, 0xf6, 0x30, 0xf6, 0x11, 0xf4, 0xb4, 0xc0, 0x05, 0xaa, 0x4a, 0xa8,
	0xb2, 0xd8, 0x3d, 0x08, 0xaf, 0x50, 0xe5, 0x02, 0x15, 0xaa, 0xd8, 0xa3, 0xd0, 0xce, 0x61, 0x59,
	0x53, 0x34, 0x8a, 0x2f, 0x48, 0xdf, 0x4b, 0x2b, 0xcb, 0xb2, 0x2e, 0x8b, 0xd5, 0x0a, 0xa5, 0xe1,
	0x2a, 0xee, 0x52, 0x57, 0xee, 0x1c, 0xc9, 0x7d, 0xe8, 0x57, 0x25, 0xb4, 0x17, 0x70, 0x39, 0xa8,
	0xaa, 0x79, 0x6b, 0x33, 0xf9, 0x06, 0xba, 0xf4, 0x7c, 0x5f, 0x40, 0xa0, 0x70, 0x86, 0xe2, 0x0a,
	0x33, 0x4a, 0xed, 0x50, 0x33, 0x6e, 0x11, 0xc9, 0x0d, 0x44, 0xfb, 0x8f, 0xca, 0xee, 0x42, 0xb8,
	0xe4, 0xe6, 0xc2, 0x35, 0x81, 0x6b, 0xfe, 0x60, 0xc9, 0x0d, 0xe1, 0x68, 0xe4, 0xaa, 0x04, 0xdc,
	0x6c, 0xd5, 0x26, 0xfb, 0x0a, 0x02, 0xf7, 0x58, 0x9b, 0x92, 0x6e, 0x77, 0x34, 0x7a, 0x7f, 0xff,
	0x99, 0xcc, 0xa6, 0x4c, 0xb7, 0xa0, 0xe4, 0x77, 0xf0, 0x9d, 0x66, 0x93, 0xd9, 0xbe, 0x05, 0xd3,
	0x4e, 0xdb, 0x9c, 0xab, 0x29, 0x52, 0x0a, 0x47, 0xef, 0x5c, 0xf0, 0x67, 0xeb, 0x4f, 0x5d, 0x38,
	0x79, 0x0d, 0x3e, 0x5d, 0x98, 0xdd, 0x87, 0xee, 0x35, 0x56, 0x73, 0x76, 0xf4, 0xce, 0x00, 0xbc,
	0x45, 0x65, 0x52, 0x0a, 0xde, 0x56, 0xf5, 0xf4, 0x35, 0x04, 0x75, 0x4e, 0xec, 0x18, 0x06, 0x6f,
	0x64, 0x86, 0x73, 0x21, 0x05, 0x2a, 0x13, 0xb5, 0x18, 0x40, 0x2f, 0xe5, 0x2b, 0x3d, 0x5b, 0x46,
	0x6d, 0x36, 0x84, 0x60, 0xc2, 0xd7, 0x94, 0x75, 0xe4, 0xb1, 0x00, 0xba, 0x6f, 0x51, 0xde, 0x44,
	0x1d, 0x16, 0x82, 0xff, 0x0c, 0x05, 0xaa, 0xa8, 0x6b, 0x9d, 0x93, 0x22, 0x2f, 0x22, 0xff, 0x74,
	0x6e, 0xc3, 0xca, 0x58, 0x81, 0x17, 0x28, 0x24, 0x2a, 0x27, 0x36, 0x11, 0x38, 0x45, 0x19, 0xb5,
	0x2d, 0xf2, 0xf1, 0x6c, 0x69, 0x9c, 0xd0, 0x2b, 0x5c, 0x4b, 0x27, 0xf4, 0x46, 0x9a, 0x5a, 0xe8,
	0x97, 0x29, 0xaa, 0xc8, 0x27, 0x81, 0x02, 0xa5, 0x58, 0x44, 0x3d, 0xeb, 0xfd, 0x0d, 0x97, 0x32,
	0xea, 0xb3, 0x3e, 0x74, 0x26, 0x7c, 0x1d, 0x05, 0xa7, 0x4f, 0xc0, 0xa7, 0xdb, 0x58, 0xdc, 0x2b,
	0x6e, 0xd6, 0x8a, 0x47, 0x2d, 0xca, 0x74, 0xb6, 0xc4, 0x3c, 0xaf, 0x8f, 0x1a, 0xa3, 0xba, 0x89,
	0x3c, 0xca, 0x54, 0x71, 0xad, 0xa3, 0x8e, 0x85, 0x9f, 0x0b, 0x8b, 0x89, 0xba, 0xa3, 0xbf, 0x3c,
	0xd8, 0x6d, 0x6e, 0xf6, 0x3d, 0x0c, 0x27, 0x76, 0xba, 0xec, 0x98, 0x08, 0xb9, 0x60, 0xcd, 0xc2,
	0xd1, 0xce, 0x3e, 0x69, 0xce, 0xeb, 0x76, 0xfb, 0x25, 0xad, 0x87, 0x6d, 0xf6, 0xad, 0x6b, 0x6d,
	0xcc, 0x25, 0x8b, 0xf7, 0x36, 0xc6, 0x76, 0x17, 0x9f, 0xfc, 0x4b, 0x30, 0x69, 0xb1, 0x1f, 0x61,
	0x48, 0x8f, 0xf0, 0x58, 0xda, 0x5f, 0x86, 0x64, 0xff, 0xb7, 0xa6, 0x0e, 0x0a, 0xfc, 0x04, 0x43,
	0xea, 0x8d, 0x6a, 0xa4, 0xd9, 0xbd, 0x7d, 0x81, 0xe6, 0x7e, 0x3f, 0xa8, 0xf0, 0x35, 0xf4, 0x27,
	0x28, 0xb3, 0x97, 0x7a, 0xc1, 0x9a, 0xdb, 0xae, 0xfa, 0x8b, 0x1d, 0xa2, 0x4c, 0x7b, 0xf4, 0xdb,
	0x7b, 0xf4, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x05, 0x78, 0x56, 0x9e, 0x09, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SchafkopfClient is the client API for Schafkopf service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SchafkopfClient interface {
	StartPlaying(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Schafkopf_StartPlayingClient, error)
	Doppeln(ctx context.Context, in *DoppelRequest, opts ...grpc.CallOption) (*Empty, error)
	SpielAnsagen(ctx context.Context, in *Spieldeklaration, opts ...grpc.CallOption) (*Empty, error)
	KarteSpielen(ctx context.Context, in *SpielKarteRequest, opts ...grpc.CallOption) (*Empty, error)
	SendMsg(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Empty, error)
}

type schafkopfClient struct {
	cc grpc.ClientConnInterface
}

func NewSchafkopfClient(cc grpc.ClientConnInterface) SchafkopfClient {
	return &schafkopfClient{cc}
}

func (c *schafkopfClient) StartPlaying(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Schafkopf_StartPlayingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Schafkopf_serviceDesc.Streams[0], "/schafkopf.schafkopf/StartPlaying", opts...)
	if err != nil {
		return nil, err
	}
	x := &schafkopfStartPlayingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Schafkopf_StartPlayingClient interface {
	Recv() (*GameEvent, error)
	grpc.ClientStream
}

type schafkopfStartPlayingClient struct {
	grpc.ClientStream
}

func (x *schafkopfStartPlayingClient) Recv() (*GameEvent, error) {
	m := new(GameEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *schafkopfClient) Doppeln(ctx context.Context, in *DoppelRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/schafkopf.schafkopf/Doppeln", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schafkopfClient) SpielAnsagen(ctx context.Context, in *Spieldeklaration, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/schafkopf.schafkopf/SpielAnsagen", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schafkopfClient) KarteSpielen(ctx context.Context, in *SpielKarteRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/schafkopf.schafkopf/KarteSpielen", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schafkopfClient) SendMsg(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/schafkopf.schafkopf/SendMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchafkopfServer is the server API for Schafkopf service.
type SchafkopfServer interface {
	StartPlaying(*Empty, Schafkopf_StartPlayingServer) error
	Doppeln(context.Context, *DoppelRequest) (*Empty, error)
	SpielAnsagen(context.Context, *Spieldeklaration) (*Empty, error)
	KarteSpielen(context.Context, *SpielKarteRequest) (*Empty, error)
	SendMsg(context.Context, *Message) (*Empty, error)
}

// UnimplementedSchafkopfServer can be embedded to have forward compatible implementations.
type UnimplementedSchafkopfServer struct {
}

func (*UnimplementedSchafkopfServer) StartPlaying(req *Empty, srv Schafkopf_StartPlayingServer) error {
	return status.Errorf(codes.Unimplemented, "method StartPlaying not implemented")
}
func (*UnimplementedSchafkopfServer) Doppeln(ctx context.Context, req *DoppelRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Doppeln not implemented")
}
func (*UnimplementedSchafkopfServer) SpielAnsagen(ctx context.Context, req *Spieldeklaration) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpielAnsagen not implemented")
}
func (*UnimplementedSchafkopfServer) KarteSpielen(ctx context.Context, req *SpielKarteRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KarteSpielen not implemented")
}
func (*UnimplementedSchafkopfServer) SendMsg(ctx context.Context, req *Message) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMsg not implemented")
}

func RegisterSchafkopfServer(s *grpc.Server, srv SchafkopfServer) {
	s.RegisterService(&_Schafkopf_serviceDesc, srv)
}

func _Schafkopf_StartPlaying_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SchafkopfServer).StartPlaying(m, &schafkopfStartPlayingServer{stream})
}

type Schafkopf_StartPlayingServer interface {
	Send(*GameEvent) error
	grpc.ServerStream
}

type schafkopfStartPlayingServer struct {
	grpc.ServerStream
}

func (x *schafkopfStartPlayingServer) Send(m *GameEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _Schafkopf_Doppeln_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoppelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchafkopfServer).Doppeln(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schafkopf.schafkopf/Doppeln",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchafkopfServer).Doppeln(ctx, req.(*DoppelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Schafkopf_SpielAnsagen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Spieldeklaration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchafkopfServer).SpielAnsagen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schafkopf.schafkopf/SpielAnsagen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchafkopfServer).SpielAnsagen(ctx, req.(*Spieldeklaration))
	}
	return interceptor(ctx, in, info, handler)
}

func _Schafkopf_KarteSpielen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpielKarteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchafkopfServer).KarteSpielen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schafkopf.schafkopf/KarteSpielen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchafkopfServer).KarteSpielen(ctx, req.(*SpielKarteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Schafkopf_SendMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchafkopfServer).SendMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schafkopf.schafkopf/SendMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchafkopfServer).SendMsg(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _Schafkopf_serviceDesc = grpc.ServiceDesc{
	ServiceName: "schafkopf.schafkopf",
	HandlerType: (*SchafkopfServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Doppeln",
			Handler:    _Schafkopf_Doppeln_Handler,
		},
		{
			MethodName: "SpielAnsagen",
			Handler:    _Schafkopf_SpielAnsagen_Handler,
		},
		{
			MethodName: "KarteSpielen",
			Handler:    _Schafkopf_KarteSpielen_Handler,
		},
		{
			MethodName: "SendMsg",
			Handler:    _Schafkopf_SendMsg_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartPlaying",
			Handler:       _Schafkopf_StartPlaying_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "schafkopf.proto",
}
